name: frontend  CI

on: 
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  build-and-docker:
    runs-on: ubuntu-latest
  
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      
      - name: show files
        run: ls -R
      
      - name: validate HTML
        run: echo "Basic validation done"

      - name: Build Step (Create dist)
        run: |
          mkdir dist
          cp index.html style.css script.js dist/
      
      - name: Check dist folder
        run: ls dist


      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: dist/

